events {}

http {
    # File mime types
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Caching configuration
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=1g inactive=60m use_temp_path=off;

    # Load balancer with 2 apache servers
    upstream backend_apache {
        server apache1:80;
        server apache2:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_apache;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Enable cache for the application
            proxy_cache my_cache;
            proxy_cache_valid 200 302 10m;
            proxy_cache_valid 404 1m;
            proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
            
            # Custom headers to visualize proxy load balancing and caching behaviors
            add_header X-Proxy-Cache $upstream_cache_status;
            add_header X-Backend-Server $upstream_addr;
        }
    }
}
